set(USER_ANALYZERS $$USRHH$$)

set(TARGET_EXEC $$EXEC$$)
set(ANA_LIBS $$ANALYZERSHH$$)

set(EXTRA_LIBS $$EXTRALIBS$$)
set(EXTRA_LIBS_DIRS $$EXTRALIBSDIRS$$)
set(EXTRA_INCLUDE_DIRS $$EXTRAINCLUDEDIRS$$)