export ANALYSISFW_PATH=$$ANALYSISFW$$
export ANALYSISFW_USERDIR=$$USERDIR$$

source $ANALYSISFW_PATH/scripts/env.sh

pathappend LD_LIBRARY_PATH $ANALYSISFW_PATH/lib-${SYSTEMINSTALL}
pathappend LD_LIBRARY_PATH $ANALYSISFW_USERDIR/lib-${SYSTEMINSTALL}
pathappend PATH $ANALYSISFW_PATH $ANALYSISFW_PATH/bin-${SYSTEMINSTALL} $ANALYSISFW_USERDIR/bin-${SYSTEMINSTALL}
