codeclimate: true
junit: true

cpp:
  cppcheck:
    enable: true
    includes: [NA62Tools/include,
               NA62Tools/Persistency/FullReco/NA62/include, # Persistency
               NA62Tools/Persistency/FullReco/Cedar/include, NA62Tools/Persistency/FullReco/CHANTI/include, NA62Tools/Persistency/FullReco/CHOD/include, # Detectors  
               NA62Tools/Persistency/FullReco/GigaTracker/include, NA62Tools/Persistency/FullReco/HAC/include, NA62Tools/Persistency/FullReco/IRC/include, 
               NA62Tools/Persistency/FullReco/LAV/include, NA62Tools/Persistency/FullReco/LKr/include, NA62Tools/Persistency/FullReco/MUV0/include, 
               NA62Tools/Persistency/FullReco/MUV1/include, NA62Tools/Persistency/FullReco/MUV2/include, NA62Tools/Persistency/FullReco/MUV3/include, 
               NA62Tools/Persistency/FullReco/NewCHOD/include, NA62Tools/Persistency/FullReco/RICH/include, NA62Tools/Persistency/FullReco/SAC/include, 
               NA62Tools/Persistency/FullReco/Spectrometer/include, 
               NA62Tools/Persistency/SlimReco/NA62/include, # Slim persistency
               NA62Tools/Persistency/SlimReco/Cedar/include, NA62Tools/Persistency/SlimReco/CHANTI/include, NA62Tools/Persistency/SlimReco/CHOD/include, # Detectors  
               NA62Tools/Persistency/SlimReco/GigaTracker/include, NA62Tools/Persistency/SlimReco/HAC/include, NA62Tools/Persistency/SlimReco/IRC/include, 
               NA62Tools/Persistency/SlimReco/LAV/include, NA62Tools/Persistency/SlimReco/LKr/include, NA62Tools/Persistency/SlimReco/MUV0/include, 
               NA62Tools/Persistency/SlimReco/MUV1/include, NA62Tools/Persistency/SlimReco/MUV2/include, NA62Tools/Persistency/SlimReco/MUV3/include, 
               NA62Tools/Persistency/SlimReco/NewCHOD/include, NA62Tools/Persistency/SlimReco/RICH/include, NA62Tools/Persistency/SlimReco/SAC/include, 
               NA62Tools/Persistency/SlimReco/Spectrometer/include, 
               NA62MC/include, NA62MC/Beam/include, NA62MC/Generator, NA62MC/MCBase/include, # MC includes
               NA62MC/Cedar/include, NA62MC/CHANTI/include, NA62MC/CHOD/include, # Detectors  
               NA62MC/GigaTracker/include, NA62MC/HAC/include, NA62MC/IRC/include, NA62MC/LAV/include, NA62MC/LKr/include, 
               NA62MC/MUV0/include, NA62MC/MUV1/include, NA62MC/MUV2/include, NA62MC/MUV3/include, 
               NA62MC/NewCHOD/include, NA62MC/RICH/include, NA62MC/SAC/include, NA62MC/Spectrometer/include, 
               NA62Reconstruction/include, NA62Reconstruction/EventDisplay/include,  NA62Reconstruction/RecoBase/include, # Reconstruction includes
               NA62Reconstruction/Service/include, NA62Reconstruction/Tools/include, 
               NA62Reconstruction/Cedar/include, NA62Reconstruction/CHANTI/include, NA62Reconstruction/CHOD/include, # Detectors  
               NA62Reconstruction/GigaTracker/include, NA62Reconstruction/HAC/include, NA62Reconstruction/IRC/include, 
               NA62Reconstruction/LAV/include, NA62Reconstruction/LKr/include, NA62Reconstruction/MUV0/include, 
               NA62Reconstruction/MUV1/include, NA62Reconstruction/MUV2/include, NA62Reconstruction/MUV3/include, 
               NA62Reconstruction/NewCHOD/include, NA62Reconstruction/RICH/include, NA62Reconstruction/SAC/include, 
               NA62Reconstruction/Spectrometer/include, 
               NA62Analysis/include, NA62Analysis/Algorithms/include, NA62Analysis/Tools/include, NA62Analysis/ToolsLib/include,
               NA62Analysis/Analyzers/CalibrationTools/include, NA62Analysis/Analyzers/DetectorAssociations/include, 
               NA62Analysis/Analyzers/Filters/include, NA62Analysis/Analyzers/MonitoringTools/include, 
               NA62Analysis/Analyzers/PhysicsTools/include, NA62Analysis/Analyzers/PreAnalyzers/include, 
               NA62Analysis/Analyzers/TestTools/include
               ]
    ignore: [unusedFunction, unusedPrivateFunction, missingOverride, noCopyConstructor, noOperatorEq, ConfigurationNotChecked]
  rats:
    enable: true
  flawfinder:
    enable: false
  lonecout:
    enable: false
    fwpaths: ["NA62Analysis", "NA62Analysis/ToolsLib"]
    anpaths: ["NA62Analysis/Analyzers/CalibrationTools", "NA62Analysis/Analyzers/DetectorAssociations", "NA62Analysis/Analyzers/Filters", 
              "NA62Analysis/Analyzers/PhysicsTools", "NA62Analysis/Analyzers/PreAnalyzers", "NA62Analysis/Analyzers/TestTools"]
    fwlevels: ["always()", "normal()", "standard()", "extended()", "debug()", "trace()"]
    anlevels: ["user_always()", "user_normal()", "user_standard()", "user()"]
python:
  flake8:
    enable: true
bash:
  shellcheck:
    enable: true
    ignore: [NA62FWBuildRunTree.py, CITests/template.sh]
fixme:
  fixme:
    enable: true
