###########################################
# MACRO FILE FOR THE INITIALIZATION PHASE #
###########################################

## Physics list options (must be specified before the run manager initialisation) ###########
#
# Available physics lists: FTFP_BERT, QGSP_BERT, QGSP_FTFP_BERT, ... (see src/PhysicsList.cc)
# Reference: http://geant4.cern.ch/support/proc_mod_catalog/physics_lists/useCases.shtml
/Simulation/Physics    QGSP_FTFP_BERT
## Other options
#/Simulation/CutsAll   1 mm
#/Simulation/CutGamma  1 mm
#/Simulation/CutEl     1 mm
#/Simulation/CutPos    1 mm
#/Simulation/CutProt   1 mm

#############################################################################################
# Description of the exotic particle (heavy neutrino, dark photon, axion, etc):
# mass [MeV], decay mode, lifetime [ns] (zero is a valid value).
# The mass must be zero for the simulation of massless neutrinos.
# In the "hnl" beam mode: lifetime is ignored, only modes 1-14 are available,
# and modes 3 and 4 include their charge conjugates.
# Valid decay modes:
#   0: stable/invisible decay (lifetime is ignored)
#   1: X --> pi+ e-
#   2: X --> pi- e+
#   3: X --> pi+ mu-
#   4: X --> pi- mu+
#   5: X --> pi0 nu
#  11: X --> rho+ e-
#  12: X --> rho- e+
#  13: X --> rho+ mu-
#  14: X --> rho- mu+
#  51: X --> e+ e- nu
#  52: X --> mu+ mu- nu
#  53: X --> e+ mu- nu
#  54: X --> e- mu+ nu
# 101: X --> e+ e-
# 102: X --> mu+ mu-
# 103: X --> pi+ pi-
# 104: X --> gamma gamma
#
/Simulation/ExoticParticle/Mass      0.0
/Simulation/ExoticParticle/DecayMode 0
/Simulation/ExoticParticle/Lifetime  1.0
#
# For K+/pi+ decay modes 3,20,30,220,230 and for "hnl" beam, generation of multiple masses
# is enabled via the MassStep [MeV] and NumberOfGeneratedParticles settings.
#
/Simulation/ExoticParticle/MassStep                   0.0
/Simulation/ExoticParticle/NumberOfGeneratedParticles 1

## Run manager initialisation ###############################################################
/run/initialize
#############################################################################################

## Output file ##############################################################################
/output/fileName pluto.root

## Beam Type ################################################################################
#
# /beam/SetBeam <Type>
# Type can be
# turtle    - the NA62 beam (default);
# matrixgun - used in the LAV matrices generation;
# exotic    - exotic particle production;
# gps       - G4 general particle source, useful for tests;
# replay    - not documented (???);
# KL        - KL beam (straight line propagation from the Be target to /decay/zMin);
# hnl       - Heavy neutral lepton production on target; 2-body decay daughters passed to G4
# external  - particles from the external file with pre-defined pdg_code,x,y,px,py,pz
# g4blout   - Geant4 Beamline output 
#############################################################################################
/beam/SetBeam turtle

## External particle beam options ###########################################################
# /beam/ExternalParticlesFile: input file name
# All files are stored in NA62Tools/Conditions/MC/ExternalGenerator
# Input file format: PDG code, x, y, z, px, py, pz
# Simulation of beam muon halo is the default option; four components are available.
# The nominal rates (in kHz) are equal to the number of particles in each file.
# halo_muons_pip.dat :   99143 mu+ from pi+ before GTK3
# halo_muons_kap.dat :   11791 mu+ from K+  before GTK3
# halo_muons_pim.dat :   21374 mu- from pi- before GTK3
# halo_muons_kam.dat :    3034 mu- from K-  before GTK3
# For simulation of the four components at the same time, use
# halo_muons.dat     :  135342 mu+- from K+-/pi+- before GTK3
/beam/ExternalParticlesFile halo_muons.dat
#############################################################################################

## Geant4 BeamLine output option ############################################################
# /beam/G4BeamStartZPosition: name of the input TTree
#                             By default, Z69200 is used corresponding to the beam composition
#                             at the position upstream the CEDAR (Z=69200mm)
#                             Available trees: Z69200
#
# /beam/G4BeamLineInputFile:  name of G4BeamLine output file name used as input
#                             The file contains TTrees with x, y, z, px, py, pz values,
#                             PDG codes of particles and their proper times at certain Z planes
#                             (for example after TAX, before Cedar etc).
#
#                             List of available files:
#                             K12_v5_Stage0_Dump_T10_NA62_MagOn_InterfaceTest_v306_9999_100000.root
#                             TTree name Z69200
#                             contains all generated particles:
#                             TTree total entries: 780559
#                             426768 pi+     |  5802 pi-
#                             147044 proton  |   101 anti_proton
#                              45995 mu-     | 95470 mu+
#                              46111 kaon+   |   198 kaon-
#                               7552 neutron |    98 anti_neutron
#                               3722 gamma   |
#                                606 e-      |   634 e+
#                                442 kaon0L  |     0 anti_kaon0
#                                  5 kaon0S  |     0 anti_kaon0
#                                  3 lambda  |     1 anti_lambda
#                                  1 sigma-  |     0 anti_sigma-
#                             and 6 events with pnnn state (pdg=1000010048)
#
#                             G4Beamline_BeamKaons.root
#                             TTree name Z69200:
#                             contains 45753 events with at least one beam kaon
#                             (momentum p>70GeV/c and initial position x,y<1mm)
#
#                             G4Beamline_BeamPions.root
#                             TTree name Z69200:
#                             contains 419559 events with at least one beam pion
#                             (momentum p>70GeV/c and initial position x,y<1mm)
# 
#                             G4Beamline_BeamParticles.root
#                             TTree name Z69200:
#                             contains 315285 events with all the other particles, not included
#                             in G4Beamline_BeamKaons.root and G4Beamline_BeamPions.root
#
# Decays of the beam particles can be forced via /decay/force
#
/beam/G4BeamStartZPosition Z69200
/beam/G4BeamLineInputFile G4Beamline_BeamKaons.root
############################################################################################# 

## TURTLE beam options ######################################################################
#
# /beam/ParticleName: Turtle beam particle name (in the Geant4 naming convention).
#                     A charged particle should be specified (e.g. kaon+, pi+, mu+, proton).
#                     If forced decay is chosen, the beam particle type must correspond
#                     to the parent for the chosen decay mode (i.e. kaon+ or pi+).
#                     Otherwise the simulation will produce an error message and stop.
#############################################################################################
/beam/ParticleName kaon+

## Matrixgun options ########################################################################
#
# /MatrixGun/particlePerBin N
#   Set the number of particle generated in a event
#   (Every event change matrix bin: see setBin command)
# /MatrixGun/channelId N
#   Select in witch LAV block generate the events
# /MatrixGun/setBin N
#   Select in witch matrix bin will generate the events
#   If without argument (or negative argument) loop over bins
# /MatrixGun/setRandomBin
#   Select a random matrix bin to every generation
# /MatrixGun/setFixedBin
#   Use single bin for all generation
# /MatrixGun/matrixLoad filename
#   Select the file path of matrix to load. It could be also an
#   empty matrix: the only relevant information is the binning
#############################################################################################

## Beam particle decay options ##############################################################
#
# /decay/force:
#
# 0   The beam particle decays according to the particle type (see /beam/particleName).
# 1   The beam particle is kaon+ or pi+ and decays within the region specified by
#     /decay/zMin and /decay/zMax, according to the mode specified by /decay/type.
#     The decay mode must be specified explicitly.
#
# /decay/muforce:
#
# 0   The daughter muon decays according to default properties
#     (with low muon decay probability due to the large lifetime).
# 1   Daughter muon proper time is capped at 0.73% (0.06%) of the mean muon lifetime
#     for kaon (pion) decays for zMin>100m, and at 0.89% (0.07%) for zMin<100.
#     Valid only for /decay/type = 30,31,230,231.
#     Simulation is sped up by a factor of 1/(1-exp(-0.73%)) = 137.487 for kaon decays,
#     and a factor of 1/(1-exp(-0.06%)) = 1667.167 for pion decays for zMin>100m.
#     For zMin<100m, these factors are 112.860 and 1429.071, respectively.

# /decay/piforce:
#
# 0   Pions from K3pi decay according to default properties.
# 1   For K3pi decays (/decay/type=10, /decay/radcor<2), pion proper time is
#     capped for two randomly chosen pions at tmax = 1.1*(Zmax-Zmin)/v*(Mpi/Epi).
#     Simulation is sped up by a factor of ~50 for the standard decay region.
# 2   For K3pi decays (/decay/type=10, /decay/radcor<2), pion proper time is
#     capped for all pions at tmax = 1.1*(Zmax-Zmin)/v*(Mpi/Epi).
#     Simulation is sped up by a factor of ~1500 for the standard decay region.
#
# /decay/type:
#
# Hadronic modes
#
#  0  K+ --> pi+ nu nu
#  1  K+ --> pi+ pi0
#  2  K+ --> pi+ pi0 gamma (IB) fully inclusive
#  3  K+ --> pi+ X0
#     X0 properties are defined via /Simulation/ExoticParticle
#  4  K+ --> pi+ pi0 A' (massless dark photon)
#
# 10  K+ --> pi+ pi+ pi-
#                 /decay/radcor:  0 not applied (default)
#                                 1 Coulomb factor
#                                 2 PHOTOS + Coulomb factor
#
# 11  K+ --> pi+ pi0 pi0
#                 /decay/radcor:  0 not applied (default)
#                                 1 applied (PHOTOS)
#
# Leptonic modes Kl2(g)
#
# 20  K+ --> e+ nu       (two-body)
#     Neutrino properties are defined via /Simulation/ExoticParticle
#
# 21  K+ --> e+ nu gamma (IB) fully inclusive as in RK definition
# 22  K+ --> e+ nu gamma (IB), Egamma > 10 MeV in kaon rest frame
#                              NB: the collinear divergency remains.
# 23  K+ --> e+ nu gamma (SD+)
# 24  K+ --> e+ nu gamma (SD-)
# 25  K+ --> e+ nu gamma (INT+)
# 26  K+ --> e+ nu gamma (INT-)
# 27  K+ --> e+ nu nu nu
#
# 30  K+ --> mu+ nu       (two-body)
#     Neutrino properties are defined via /Simulation/ExoticParticle
# 31  K+ --> mu+ nu gamma (IB) fully inclusive as in RK definition
# 32  K+ --> mu+ nu gamma (IB), Egamma > 10 MeV in kaon rest frame
# 33  K+ --> mu+ nu gamma (SD+)
# 34  K+ --> mu+ nu gamma (SD-)
# 35  K+ --> mu+ nu gamma (INT+)
# 36  K+ --> mu+ nu gamma (INT-)
# 37  K+ --> mu+ nu nu nu
# 38  K+ --> mu+ nu A'
#     Dark photon (A') properties are defined via /Simulation/ExoticParticle
#
# Semileptonic modes Kl3(g)
#
# 40  K+ --> pi0 e+ nu  (Ke3)
#                 /decay/radcor:  0 not applied (default)
#                                 1 applied (PHOTOS+Ginsberg)
# 41  K+ --> pi0 mu+ nu (Kmu3)
#                 /decay/radcor:  same as for mode 40
# 42  K+ --> pi0 e+ nu gamma  (from KLOE library)
# 43  K+ --> pi0 mu+ nu gamma (from KLOE library)
# 44  K+ --> pi0 e+ nu gamma  (IB and DE and their interference)
#
# Semileptonic modes Kl4
#
# 60  K+ --> pi+ pi- e+ nu (Ke4)
#                 /decay/radcor:  0 not applied (default)
#                                 1 applied (PHOTOS)
# 61  K+ --> pi0 pi0 e+ nu (Ke4)
#                 /decay/radcor:  same as for mode 60
#
# Kl4: Ferrara 1-loop ChPT generators
#
# 70  K+ --> pi+ pi- e+ nu (Ke4)
# 71  K+ --> pi0 pi0 e+ nu (Ke4)
# 72  K+ --> pi+ pi- mu+ nu (Kmu4)
# 73  K+ --> pi0 pi0 mu+ nu (Kmu4)
#
# Hadronic modes with photons
#
# 80  K+ --> pi+ pi0 gamma (IB), Egamma>10MeV in kaon rest frame
# 81  K+ --> pi+ pi0 gamma (DE)
# 82  K+ --> pi+ pi0 gamma (INT)
# 83  K+ --> pi+ gamma gamma
# 84  K+ --> pi+ gamma e+ e-
# 85  K+ --> pi+ gamma mu+ mu-
# 86  K+ --> pi+ pi0 e+ e- (IB)
# 87  K+ --> pi+ pi+ pi- gamma, Egamma>1MeV in kaon rest frame
#
# Four-lepton modes: not validated
#
# 100 K+ --> e+  nu e+  e-
# 101 K+ --> mu+ nu e+  e-
# 102 K+ --> e+  nu mu+ mu-
# 103 K+ --> mu+ nu mu+ mu-
#
# FCNC modes with l+l-
#
# 120 K+ --> pi+ e+ e-
#                 /decay/radcor:  0 not applied (default)
#                                 1 PHOTOS
#                                 2 PHOTOS + Coulomb
# 121 K+ --> pi+ mu+ mu-
#                 /decay/radcor:  0 not applied (default)
#                                 2 Coulomb
#
# LFV and LNV modes: flat distribution over phase space
#
# 130 K+ --> pi+ mu+ e-
# 131 K+ --> pi+ mu- e+
# 132 K+ --> pi- mu+ e+
# 133 K+ --> pi- e+  e+
# 134 K+ --> pi- mu+ mu+
#
# 140 K+ --> e-  nu mu+ mu+
# 141 K+ --> mu- nu e+  e+
#
# Beam pi+ decays: pi+ --> l+ nu (g)
#
# 220 pi+ --> e+ nu       (two-body)
#     Neutrino properties are defined via /Simulation/ExoticParticle
# 221 pi+ --> e+ nu gamma (IB) fully inclusive as in RK definition
# 222 pi+ --> e+ nu gamma (IB), Egamma>10MeV in kaon rest frame
#                               NB: the collinear divergency remains.
# 223 pi+ --> e+ nu gamma (SD+)
# 224 pi+ --> e+ nu gamma (SD-)
# 225 pi+ --> e+ nu gamma (INT+)
# 226 pi+ --> e+ nu gamma (INT-)
# 227 pi+ --> e+ nu nu nu
#
# 230 pi+ --> mu+ nu       (two-body)
#     Neutrino properties are defined /Simulation/ExoticParticle
# 231 pi+ --> mu+ nu gamma (IB) fully inclusive as in RK definition
# 232 pi+ --> mu+ nu gamma (IB), Egamma>10MeV in kaon rest frame
# 233 pi+ --> mu+ nu gamma (SD+)
# 234 pi+ --> mu+ nu gamma (SD-)
# 235 pi+ --> mu+ nu gamma (INT+)
# 236 pi+ --> mu+ nu gamma (INT-)
# 237 pi+ --> mu+ nu nu nu
#
# KL decays
#
# 300 KL --> pi+ pi-
# 301 KL --> pi0 pi0
# 302 KL --> pi+ pi- pi0
# 303 KL --> pi0 pi0 pi0
#
# 320 KL --> e+  e-
# 321 KL --> mu+ mu-
# 322 KL --> e+ mu- (LFV)
# 323 KL --> mu+ e- (LFV)
#
# 340 KL --> pi0 e+ e-
# 341 KL --> pi0 mu+ mu-
# 342 KL --> pi0 e+ mu- (LFV)
# 343 KL --> pi0 mu+ e- (LFV)
#
#
# Muon polarization is simulated for modes 30,31,230,231.
# /decay/muonDecay:   controls the simulation of muon decays.
#                     Valid muon decay modes:
#                      0: G4MuonDecayChannelWithSpin (polarization + 1st order radiative corrections)
#                      1: G4MuonDecayChannelWithSpin*0.986 + MuonRadiativeDecayChannelWithSpinWithEgammaCut*0.014
#                         (polarization + 1st order radiative corrections + radiative mu->enunug decay, Eg>10MeV)
#                      2: MuonRadiativeDecayChannelWithSpinWithEgammaCut (only radiative mu->enunug decay, Eg>10MeV)
#                      3: Custom mu->enunu(g) decay (polarization + IB consistently with the RK definition)
#                         WARNING: this generator is not ready yet!
#                         The current implementation is just a copy of G4MuonDecayChannelWithSpin!
#
# /decay/BrPie2: BR(pi+- --> e+- nu). The PDG value is 1.23e-4.
#                Two pi+- decay modes are simulated: (e+- nu) and (mu+- nu).
#
# /decay/pizeroDecay: controls the simulation of decays of pi0's from the kaon decay.
#                     Exactly 3 parameters corresponding to 3 pi0's must be specified.
#                     Excess parameters are ignored in case of fewer pi0's in the final state.
#                     For an explanation of the pi0 Dalitz decay options, see Generator/pi0Dalitz.cc(.hh)
#                     Valid pi0 decay modes:
#                      0: pi0 is passed to Geant4 (BR(gg)=0.988, BR(ge+e-)=0.012,
#                         zero FF slope, no rad.corr., decay products not saved into GeneParts);
#                      1: pi0-->gg;
#                     11: pi0-->ge+e-    (Dalitz decay, no radiative corrections);
#                     12: pi0-->ge+e-    (Dalitz decay, Mikaelian-Smith + one photon irreducible corrections);
#                     13: pi0-->ge+e-(g) (Dalitz decay, radiative decay, full radiative corrections);
#                     14: pi0-->ge+e-g   (Dalitz decay, 4-body decay with a radiative photon);
#                     15: pi0-->ge+e-    (Dalitz decay with x>0.5, Mikaelian-Smith + one photon irreducible corrections);
#                     16: pi0-->ge+e-(g) (Dalitz radiative decay with x>0.5, full radiative corrections);
#                     21: pi0-->e+e-     (no radiative corrections);
#                     22: pi0-->e+e-(g)  (radiative decay);
#                     31: pi0-->e+e-e+e- (double Dalitz decay, no radiative corrections);
#                     32: pi0-->e+e-e+e- (double Dalitz decay, LO+NLO radiative corrections);
#                     41: pi0-->mu+e-    (LFV);
#                     42: pi0-->mu-e+    (LFV);
#                     51: pi0-->3g       (flat phase space);
#                     52: pi0-->4g       (flat phase space);
#                     53: pi0-->g nu nu  (SM spectrum);
#                     90: pi0-->g X0     (X0 properties defined via /Simulation/ExoticParticle);
#                     99: pi0-->invisible particles.
#                     Default = (0, 0, 0).
#                     Requesting a non-specified decay mode is equivalent to mode=0.
#
# /decay/zMin, /decay/zMax: z coordinate of the beginning and end of the decay region [mm].
#                           These values are effective for forced decay only.
#                           These values are simulated approximately: they refer to beam particle
#                           path length, not the z coordinate. Typically the smallest and largest generated
#                           z positions of the decay vertices are a few mm smaller than zMin and zMax, respectively.
#                           Defaults: zMin=102425mm (end of GTK responsibility region),
#                                     zMax=180000mm (upstream of straw chamber 1).
# /decay/verbose: verbosity level passed to the Generator level (CMC)
#
# Biasing options (no biasing is performed for negative paremeter values):
#
# /decay/RadiativePhotonMinEnergy: Lower limit for the radiative photon energy [MeV] in K rest frame.
#                                  Implemented for decay modes 2, 42, 44.
#
# /decay/RadiativePhotonMaxEnergy: Upper limit for the radiative photon energy [MeV] in K rest frame.
#                                  Implemented for decay mode 2.
#
# /decay/twoPhotonsMaxAngle: Biasing for decay modes with photons by asking at least one photon pair
#                            to form an angle smaller than the value set for twoPhotonsMaxAngle [rad].
#                            Implemented for decay modes 2, 11, 80, 81, 82.
#
# /decay/LeptonPhotonMinAngle: Lower limit for the lepton-photon angle in K rest frame [rad].
#                              Implemented for decay modes 42, 44.
#
# /decay/MinTracksMomentum: Minimal sum of momenta of the charged tracks [MeV].
#                           Implemented for decay modes 2, 42, 43.
#
#############################################################################################
/decay/force 1
/decay/muforce 0
/decay/piforce 0
/decay/type DECAYTYPE
/decay/pizeroDecay 1 1 1
/decay/radcor 0
/decay/muonDecay 1
/decay/BrPie2 1.23e-4
/decay/zMin 102425.
/decay/zMax 180000.
/decay/verbose 0
/decay/RadiativePhotonMinEnergy -1
/decay/RadiativePhotonMaxEnergy 500
/decay/twoPhotonsMaxAngle -1
/decay/LeptonPhotonMinAngle -1
/decay/MinTracksMomentum -1

## Detector options #########################################################################
# All SubDetectors are disabled by default.
# /Detector/EnableSubDetector <name>, /Detector/DisableSubDetector <name>
# allow to enable/disable them individually.
#############################################################################################

/Detector/PathToLKrShowersDb /cvmfs/na62.cern.ch/offline/NA62FW/showers.db

/Detector/EnableSubDetector Cedar
/Detector/EnableSubDetector CHANTI
/Detector/EnableSubDetector CHOD
/Detector/EnableSubDetector GigaTracker
/Detector/EnableSubDetector HAC
/Detector/EnableSubDetector IRC
/Detector/EnableSubDetector LAV
/Detector/EnableSubDetector LKr
/Detector/EnableSubDetector RICH
/Detector/EnableSubDetector MUV0
/Detector/EnableSubDetector MUV1
/Detector/EnableSubDetector MUV2
/Detector/EnableSubDetector MUV3
/Detector/EnableSubDetector NewCHOD
/Detector/EnableSubDetector SAC
/Detector/EnableSubDetector Spectrometer

## Magnetic fields ##########################################################################
#
# Scale factors of the blue tube and MNP33+fringe magnetic fields (defaults=1.0).
# /Detector/MagneticField/MNP33/Detailed defines the MNP33+fringe magnetic field model:
# detailed according to field map measurements ("true", default),
# or uniform vertical field confined to a 1.3 m long volume with no fringe field ("false").
#############################################################################################
/Detector/MagneticField/BlueTube/Scale 1.0
/Detector/MagneticField/MNP33/Detailed true
/Detector/MagneticField/MNP33/Scale    1.0

## Two-step ("fast") simulation: not currently supported ####################################
## Step 1 means simulation of CEDAR, GTK and STRAW
## Step 2 means simulation of all the other detectors
## Input file is mandatory for Step 2
## Any other number means standard simulation accordingly to previously enabled detectors
#/fastSimu/StepNo 0
#/fastSimu/InputFile input.root

#/Simulation/TurnOnFastLkr

## Cedar options ############################################################################
#
# Enable the Cherenkov effect in the Cedar: true (default) or false
#
#############################################################################################
/Detector/Cedar/EnableCherenkovEffect true

## LAV options ##############################################################################
#
# ### Select which parts of the LAV should be used ###
# All stations/vessels/layers/bananas are enabled by default
#
# # Stations
#   - <s> goes from 0 (LAV station 1) to 11 (LAV station 12)
# /Detector/LAV/EnableAllStations
# /Detector/LAV/DisableAllStations
# /Detector/LAV/EnableStation <s>
# /Detector/LAV/DisableStation <s>
# # Vessels
#   - <s> as for Stations
# /Detector/LAV/EnableAllVessels
# /Detector/LAV/DisableAllVessels
# /Detector/LAV/EnableVessel <s>
# /Detector/LAV/DisableVessel <s>
# # Layers
#   - <s> as for Stations
#   - <l> goes from 0 to 4 for stations 1-8, from 0-3 for stations 9-12
# /Detector/LAV/EnableAllLayers
# /Detector/LAV/DisableAllLayers
# /Detector/LAV/EnableLayer <s> <l>
# /Detector/LAV/DisableLayer <s> <l>
# # Bananas
#   - <s> as for Stations
#   - <l> as for Layers
#   - <b>: 0-7 for stations 1-5, 0-11 for stations 6-8,
#          0-14 for stations 9-11, 0-15 for station 12
# /Detector/LAV/EnableAllBananas
# /Detector/LAV/DisableAllBananas
# /Detector/LAV/EnableBanana <s> <l> <b>
# /Detector/LAV/DisableBanana <s> <l> <b>
#
# Example: use only LAV station 3 (<s>=2)
# /Detector/LAV/DisableAllStations
# /Detector/LAV/EnableStation 2
#
# Example: use only layer 4 of station 3 (<s>=2), do not use steel vessel
# /Detector/LAV/DisableAllStations
# /Detector/LAV/DisableAllLayers
# /Detector/LAV/EnableStation 2
# /Detector/LAV/EnableLayer 2 4
# /Detector/LAV/DisableVessel 2
#
# ### Select how the PbGl block should be simulated
#   - <method> can be:
#     standard - approximate optical photons tracking using map files (fast, default)
#     optical  - do full tracking of optical photons (slow)
# /Detector/LAV/SelectBlockSimulation <method>
#
# ### Select matrices for standard simulation ###
#/Detector/LAV/EfficiencyMatrix ./LAV/LAVEff.txt
#/Detector/LAV/TimeMatrix ./LAV/LAVDelay.txt
#############################################################################################

### LKr Digitization ########################################################################
#
# Files to convert the energy deposition in one LKr cell into a current signal
#
#############################################################################################
/Detector/LKr/GeVtoCurrent1 LKrGeVtoCurr1.dat
/Detector/LKr/GeVtoCurrent2 LKrGeVtoCurr2.dat
/Detector/LKr/GeVtoCurrent3 LKrGeVtoCurr3.dat

### Enable MUV1 full optical simulation #####################################################
#
# Full optical simulation disabled by default:
#
#  <flag> = false - No photons are produced, saving information for parametrization (default)
#           true  - Full optical simulation (very slow, not recommended)
#
#############################################################################################
/Detector/MUV1/EnableFullOpticalSimulation false

## Fast simulation configuration ############################################################
# 0: normal simulation
# 1: fast simulation: detectors downstream Spectrometer disabled,
#    Cherenkov light in Cedar switched off (~60 times faster simulation)
# 2: same as 1, with the RICH detector enabled (~20 times faster simulation)
/Detector/FastSimulationMode 0

### User beam (for testing purposes) ########################################################
#
# Several examples are provided below. Further examples of setting up
# the GPS (General Particle Source) beams can be found e.g. here:
# http://goudzovs.web.cern.ch/goudzovs/GPS-beams.pdf
#
#/beam/SetBeam gps
#
# Irradiation with a halo
#
#/gps/particle geantino
#/gps/ene/type Mono
#/gps/ene/mono 1 GeV
#/gps/pos/type Plane
#/gps/pos/shape Rectangle
#/gps/pos/halfx 1000 mm
#/gps/pos/halfy 1000 mm
#/gps/pos/centre 0 0 0 m
#/gps/direction 0 0 1
#
# A monochromatic pencil beam
#
#/gps/particle geantino
#/gps/position 0 0 66 m
#/gps/ene/mono 10.0 GeV
#/gps/direction 0 0 1
#
# The incident surface is in the x-y plane
#
#/gps/pos/type Beam
#/gps/pos/rot1 1 0 0
#/gps/pos/rot2 0 1 0
#
# The beam spot is centered at few cm upstream the RICH and is
# of 1d gaussian shape with a 1mm central plateau
#
#/gps/pos/shape Circle
#/gps/pos/centre  0 0.2 215 m
#/gps/pos/radius 1. mm
#/gps/pos/sigma_r .1 mm
#
# The beam is travelling along the Z axis with 20 microrad dispersion
#
#/gps/ang/rot1 0 1 0
#/gps/ang/rot2 1 0 0
#/gps/ang/type beam1d
#/gps/ang/sigma_r 20e-6 rad
#
# The beam energy has a gaussian profile
#
#/gps/ene/type Gauss
#/gps/ene/mono 10.0 GeV
#/gps/ene/sigma 100. MeV
#
#/tracking/verbose 1
#############################################################################################

## Handling of KineParts ####################################################################
## The following commands are listed in order of priority of execution.
## 1. The beam particle is always stored.
##
## 2. Save all steps or all tracks. If all steps are saved, then tracks are not saved.
/kine/SaveAllSteps false
/kine/SaveAllTracks false
##
## 3. For anything to be stored, the beam particle end process must not be one of those below.
## Partial name match is sufficient in this category: for example,
## "Inelastic" suppresses all inelastic interactions (kaon+Inelastic, pi+Inelastic, etc),
/kine/BeamParticleEndProcessToReject Inelastic
##
## 4. For anything to be stored, the beam particle endpoint should be in the following range [mm].
/kine/zMinBeamForKineParts 69175.
/kine/zMaxBeamForKineParts 300000.
##
## 5. Two generations of decay daughters of the beam particle are always stored.
##
## 6. Particles that should always be kept:
##    by particle name; by creator process; by end process
#/kine/ParticleTypeToSave pi+
#/kine/CreatorProcessToSave Decay
#/kine/EndProcessToSave Decay
##
## 7. Particles that should be rejected:
##    by particle name; by creator process; by end process
## Partial name match is sufficient in this category: for example,
## "Inelastic" suppresses all inelastic interactions (kaon+Inelastic, pi+Inelastic, etc),
## and "nu_e" suppresses also "anti_nu_e"
/kine/ParticleTypeToReject nu_mu
/kine/ParticleTypeToReject nu_e
/kine/ParticleTypeToReject opticalphoton
/kine/CreatorProcessToReject Inelastic
/kine/CreatorProcessToReject Brem
/kine/CreatorProcessToReject Nuclear
/kine/CreatorProcessToReject Ioni
/kine/CreatorProcessToReject PairProd
/kine/CreatorProcessToReject annihil
/kine/EndProcessToReject Scintillation
##
## 8. The remaining particles are saved if
##    - energy is above MinimumEnergy (in MeV),
##    - interaction level is less or equal to MaximumInteractionLevel.
##    Interaction level is 0 for the beam and increments by 1 for each secondary particle
/kine/MinimumEnergy 0.0
/kine/MaximumInteractionLevel 2
##
## Print information for each track (default=false)
/kine/SaveTrackVerbose false

##### Do not remove this! #####
/Detector/UpdateGeometry

## Random Generator #########################################################################
/random/seed SEED

## Number of events #########################################################################
/run/beamOn NEVENTS
#############################################################################################
