MACRO(SUBDIRLIST dir result)
	FILE(GLOB children ${dir}/*)
	FILE(GLOB svn ${dir}/.svn)
	IF(NOT "${svn}" STREQUAL "") 
	    LIST(REMOVE_ITEM children ${svn})
	ENDIF()
	SET(dirlist "")
	FOREACH(child ${children})
		IF(IS_DIRECTORY ${child})
			SET(dirlist ${dirlist} ${child})
		ENDIF()
	ENDFOREACH(child)
	SET(${result} ${dirlist})
ENDMACRO()


MACRO(GETGCCVERSION major minor)
    execute_process(COMMAND ${CMAKE_C_COMPILER} -dumpversion
                    OUTPUT_VARIABLE GCC_VERSION)
    string(REGEX MATCHALL "[0-9]+" GCC_VERSION_COMPONENTS ${GCC_VERSION})
    list(GET GCC_VERSION_COMPONENTS 0 GCC_MAJOR)
    list(GET GCC_VERSION_COMPONENTS 1 GCC_MINOR)

	SET(${major} ${GCC_MAJOR})
	SET(${minor} ${GCC_MINOR})
ENDMACRO()

MACRO(EXCLUDEEMACS filelist)
	FOREACH(f ${${filelist}})
		IF(${f} MATCHES ".*#.*")
			list(REMOVE_ITEM ${filelist} ${f})
		ENDIF()
	ENDFOREACH(f)
ENDMACRO()

MACRO(LIST_ALL_VARIABLES)
    get_cmake_property(_variableNames VARIABLES)
    foreach (_variableName ${_variableNames})
        message(STATUS "${_variableName}=${${_variableName}}")
    endforeach()
ENDMACRO()

FUNCTION(PREPEND_LIST var prefix)
   SET(listVar "")
   FOREACH(f ${${var}})
      LIST(APPEND listVar "${prefix}${f}")
   ENDFOREACH(f)
   SET(${var} "${listVar}" PARENT_SCOPE)
ENDFUNCTION(PREPEND_LIST)

FUNCTION(APPEND_LIST var postfix)
   SET(listVar "")
   FOREACH(f ${${var}})
      LIST(APPEND listVar "${f}${postfix}")
   ENDFOREACH(f)
   SET(${var} "${listVar}" PARENT_SCOPE)
ENDFUNCTION(APPEND_LIST)

FUNCTION(SANDWICH_LIST var prefix postfix)
   SET(listVar "")
   FOREACH(f ${${var}})
      LIST(APPEND listVar "${prefix}${f}${postfix}")
   ENDFOREACH(f)
   SET(${var} "${listVar}" PARENT_SCOPE)
ENDFUNCTION(SANDWICH_LIST)

FUNCTION(KEEPFILENAMES_LIST var)
   SET(listVar "")
   FOREACH(f ${${var}})
   	  GET_FILENAME_COMPONENT(f ${f} NAME)
      LIST(APPEND listVar ${f})
   ENDFOREACH(f)
   SET(${var} "${listVar}" PARENT_SCOPE)	
ENDFUNCTION(KEEPFILENAMES_LIST)