unsigned short isGlobalHeader(unsigned long );
unsigned short isGlobalTrailer(unsigned long );
int TriggerNumber(unsigned long );
unsigned int BoardNumber(unsigned long );
unsigned short isTDCHeader(unsigned long );
unsigned short isTDCTrailer(unsigned long );
unsigned short isTDCError(unsigned long );
unsigned int TDCChip(unsigned long );
unsigned int EventId(unsigned long );
unsigned int BunchId(unsigned long );
short TDCWordCount(unsigned long );
unsigned short isMeasurement(unsigned long );
unsigned short isTrailing(unsigned long ) ;
int ChannelNumber(unsigned long );
long ChannelValue(unsigned long );
unsigned long TDCErrorBits(unsigned long );
unsigned short isTriggerTimeTag(unsigned long );
unsigned long ExtendedTriggerTime(unsigned long );
unsigned short Overflow(unsigned long );
unsigned short Error(unsigned long );
unsigned short Lost(unsigned long );
unsigned long EventSize(unsigned long );
unsigned short isFiller(unsigned long );
unsigned short isScalerHeader(unsigned long );
unsigned short isScalerTrailer(unsigned long );
