unsigned short isLKrBlock(unsigned int );
unsigned short isToBeDecoded(unsigned int );
unsigned int TrigNumber(unsigned int );
unsigned int TrigWord(unsigned int );
unsigned int ChannelId(unsigned int );
unsigned int TimeStamp(unsigned int );
unsigned int RioHeader(unsigned int, unsigned int);
unsigned int RioTrailer(unsigned int, unsigned int);
unsigned short RioNChannels(unsigned int );
unsigned short BlockLength(unsigned int );

//  Functions to handle CPD ids and coordinates
int xcha_scha(int);
int ycha_scha(int);
int xcpd_scpd(int);
int ycpd_scpd(int);
int xchacpd_schacpd(int);
int ychacpd_schacpd(int);
int xcha_scpd_schacpd(int,int);
int ycha_scpd_schacpd(int,int);
int xcha_scpd_schacpd(int,int);
int schacpd_xchacpd_ychacpd(int,int);
int xchacpd_xcha(int);
int ychacpd_ycha(int);
int schacpd_xcha_ycha(int,int);
int schacpd_scha(int);
int xcpd_xcha(int);
int ycpd_ycha(int);
int scpd_xcpd_ycpd(int,int);
int scpd_xcha_ycha(int,int);
int scpd_scha (int);
